version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: namachan10777/naml:latest

    working_directory: ~/naml

    steps:
      - checkout

      - run:
          name: test 1st
          command: eval $(opam env) && make test
